apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-first-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: my-first-app # ЭТОТ БЛОК НЕЛЬЗЯ УДАЛЯТЬ
  template:
    metadata:
      labels:
        app: my-first-app # ДОЛЖНО СОВПАДАТЬ С SELECTOR ВЫШЕ
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/port: "80"
    spec:
      imagePullSecrets:
        - name: harbor-registry-secret
      containers:
        - name: nginx
          image: 192.168.3.149:80/devops-lab/test-image:v32
          imagePullPolicy: Always
          ports:
            - containerPort: 80

